version: '3.8'
services:
    web:
        build:
            context: ./web
            dockerfile: Dockerfile
        ports:
            - "5173:80"
        volumes:
            - ./web/nginx.conf:/etc/nginx/nginx
        networks:
            - sarti-network
        environment:
            - VITE_API_BASE_URL: http://3.211.99.137:8081/api/sarti
networks:
    sarti-network:
        driver: bridge