version: '3.8'
services:
    web:
        build:
            context: ./web
            dockerfile: Dockerfile
        ports:
            - "5173:80"
        volumes:
            - ./web/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - sarti-network
        environment:
            - VITE_API_BASE_URL=http://18.204.251.12:8081/api/sarti
        restart: always
networks:
    sarti-network:
        driver: bridge
